[workspace]
resolver = "3"
members = ["./crates/*/", "foo", "bar"]

[workspace.package]
edition = "2024"
authors = ["kohdice"]
repository = "https://github.com/kohdice/cargo-workspaces-sample"

[workspace.dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.31", features = ["derive"] }
